# -*- coding: utf-8 -*-
"""cnn1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11sK7oJs0pMJSgYhaxprjorFpWEKsvLNE
"""

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
from matplotlib import pyplot as plt
import numpy as np



device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

trainsform = transforms.Compose([
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(15),
    transforms.ColorJitter(0.2,0.2,0.2),
    transforms.ToTensor(),
    transforms.Normalize((0.5,0.5,0.5),(0.5,0.5,0.5))
])

train_dataset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=trainsform)
test_dataset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=trainsform)

train_loader = DataLoader(train_dataset , batch_size=100,shuffle=True)
test_loader = DataLoader(dataset=test_dataset, batch_size=100, shuffle=False)

from torch.nn.modules.pooling import MaxPool2d
class cnn(nn.Module):
  def __init__(self):
    super().__init__()
    self.model = nn.Sequential(
        nn.Conv2d(3,32, kernel_size=(3,3),padding='same'),
        nn.ReLU(),
        nn.MaxPool2d(kernel_size=(2,2), stride=(2,2)),
        nn.Dropout(0.25),

        nn.Conv2d(32,64, kernel_size=(3,3),padding='same'),
        nn.ReLU(),
        nn.MaxPool2d(kernel_size=(2,2), stride=(2,2)),
        nn.Dropout(0.25),

    )
    self.fc_layer = nn.Sequential(
        nn.Flatten(),
        nn.Linear(64*8*8,600),
        nn.ReLU(),
        nn.Dropout(0.25),
        nn.Linear(600,120),
        nn.ReLU(),
        nn.Dropout(0.25),
        nn.Linear(120,10)
    )
  def forward(self,x):
      x = self.model(x)
      x= self.fc_layer(x)
      return x



model = cnn().to(device)
loss_fn = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(),lr = 0.001)
num_epochs = 10
total_step = len(train_loader)

for epoch in range(30):
  for x,y in  train_loader:
    x = x.to(device)
    y = y.to(device)
    output = model(x)
    loss = loss_fn(output,y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

model.eval()
with torch.no_grad():
  correct = 0
  total = 0 # Changed 'totoal' to 'total'
  for x,y in test_loader:
    x = x.to(device)
    y = y.to(device)
    output = model(x)
    _,prediction = torch.max(output.data,1)
    total += y.size(0)
    correct += (prediction == y).sum().item() # Corrected comparison to (prediction == y)
  print(f"Accuracy of the model on the {len(test_dataset)} test images: {100 * correct / total:.2f}%") # Used 'total' and len(test_dataset)

